In [1]:
import numpy as np

روش های ساخت ارایه

In [16]:
a = [[1,2,3],[4,5,6]]
x = np.array(a)
y = np.arange(6).reshape(2, 3)
zx = np.full((2, 3), 0)
z = np.identity(5)
np.concatenate((x, y), axis=1)

array([[4.24399158e-314, 1.48219694e-323, 4.24399158e-314],
       [1.06099790e-313, 6.36598738e-314, 1.06099790e-313]])

In [3]:
x.shape
x.itemsize
len(x)

2

تغییرات روی ارایه

In [4]:
x.flatten()تک بعدی سازی
x.diagonal()
np.append(x, [[9, 10, 11]], axis=0)
np.delete(x, 1, axis=0)
np.insert(x, 0, [[11]], axis=0)


array([[11, 11, 11],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [5]:
v = np.array([1,1,1,3,3,3,7,7,7])
np.unique(v)

array([1, 3, 7])

string

In [6]:
np.char.join("*", "hi everyone hi")
np.char.add(["hi"], ["bey"])
np.char.title("dfhjd idfoi djfalj")
a = np.char.replace("my name is zahra", "zahra", "lili")
print(np.char.capitalize(a))

My name is lili


Create a vector with values ranging from 10 to 49

In [7]:
x = np.arange(10, 50)
x[::-1] #revers

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3x3 matrix with values ranging from 0 to 8 

In [8]:
x = np.arange(0, 9)#.reshape(3, 3)
y = np.array(np.split(x,3))
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

مکان غیر اعداد غیر صفر

In [9]:
x = np.array([1,2,0,0,4,0])
j = 0
for i in x:
    if(i != 0):
        print(j , end=" ")
    j += 1

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

0 1 4 (array([0, 1, 4], dtype=int64),)


In [10]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3 array with random values

In [11]:
x = np.random.random((3,3))
x.min()
x.max()
x.mean()

0.4775079823936799

Create a 5x5 matrix with values 1,2,3,4 just below the diagona

In [32]:
x = np.diag(1 + np.arange(5), k=0)
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [13]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 7 8]


In [14]:
x = np.datetime64('today')
x

numpy.datetime64('2023-07-12')

In [15]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(Z)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [37]:
d =np.empty(5)
np.random.randn(2,3)
np.arange(20).reshape((4,5))
x = [1,2,3,4,4]
x = np.array(x, dtype=float)
y =np.fmin(x, d)
y

array([1., 2., 3., 4., 4.])